services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: true

  App\:
    resource: '../src/*'
    exclude: '../src/{Kernel.php}'

  Symfony\Component\HttpFoundation\Request:
    factory: 'App\Factory\HttpRequestFactory:create'

  Amirax\Base62Interface:
    class: Amirax\Base62